### ISSUE TITLE
React to changes in K8S

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#464]
So, if the sync-loop is on, and someone does a `kubectl apply` which conflicts, it should be fixed.

**Comment by paulbellamy** [comment]
Depends on https://github.com/weaveworks/flux/issues/463

**Comment by philwinder** [comment]
**Use case**
If the K8s cluster is altered in some way (a user changes the configuration of a deployment, for example), this should trigger a Sync.

**Responsibilities**
- Monitor the k8s lifecycle
- Upon a change (any change?) it will trigger a sync
- Avoid triggering on events that were intentional (e.g. a previous sync)

**Tasks**
- [ ] Investigate k8s event api
- [ ] Subscribe to events
- [ ] Code resides in fluxd
- [ ] Define what counts as "a change"
- [ ] Call hook url when changed (how to get hook url?)
- [ ] Consider steps to avoid recursive triggers (change causes trigger, causes change, etc.)

**Comment by philwinder** [comment]
**Research**
The code is currently using 1.5 of the K8s api, accessed through the 1.5 version of the `go-client` library. It doesn't appear possible to access the v1beta1 api through the helpers in the library, so it will be necessary to implement your own URL factory. Also, it is not possible to watch all events, only specific ones. So you have to pick which resources you want to watch and write watchers for each type. Below is an example of how to do that for a single resource type:

```go
import (
	k8kubernetes "k8s.io/client-go/1.5/kubernetes"
	"k8s.io/client-go/1.5/pkg/api"
	"k8s.io/client-go/1.5/pkg/apis/extensions/v1beta1"
	"k8s.io/client-go/1.5/pkg/fields"
	"k8s.io/client-go/1.5/pkg/runtime"
	"k8s.io/client-go/1.5/pkg/watch"
	"k8s.io/client-go/1.5/rest"
	"k8s.io/client-go/1.5/tools/cache"
)
...
	restClientConfig, err := rest.InClusterConfig()
...

		clientset, err := k8kubernetes.NewForConfig(restClientConfig)
		if err != nil {
			panic(err.Error())
		}
// A blank namespace watches all namespaces
// Cannot leave resource type string empty
		watchlist := cache.NewListWatchFromClient(clientset.Core().GetRESTClient(), "services", "", fields.Everything())
		_, controller := cache.NewInformer(
			watchlist,
			&v1.Service{},
			time.Second*0,
			cache.ResourceEventHandlerFuncs{
				AddFunc: func(obj interface{}) {
					fmt.Printf("add: %s \n\n", obj)
				},
				DeleteFunc: func(obj interface{}) {
					fmt.Printf("delete: %s \n\n", obj)
				},
				UpdateFunc: func(oldObj, newObj interface{}) {
					fmt.Printf("old: %s, new: %s \n\n", oldObj, newObj)
				},
			},
		)
		stop := make(chan struct{})
		go controller.Run(stop)
```

**Comment by philwinder** [comment]
**Research**
The 2.0 version of the `client-go` library has a similar structure. Certain structs have been moved to other packges, but the use of the `Informer` and `ListWatch` are the same.

**Comment by philwinder** [comment]
**Research**
It is possible to tap into the events api with:
```
		_, controller := cache.NewInformer(
			&cache.ListWatch{
				ListFunc: func(options api.ListOptions) (runtime.Object, error) {
					return clientset.Events(ns).List(v1.ListOptions{})
				},
				WatchFunc: func(options api.ListOptions) (watch.Interface, error) {
					return clientset.Events(ns).Watch(v1.ListOptions{})
				},
			},
			&v1.Event{},
			time.Second*0,
			cache.ResourceEventHandlerFuncs{
```
However, creating or deleting a service does not cause a new item in the event log.

**Comment by philwinder** [comment]
**Conclusion**
Create a list of types we are interested in, then create a [watcher](https://github.com/weaveworks/flux/issues/464#issuecomment-292482103) for those distinct types.

- [ ] Pods
- [ ] Deployments
- [ ] Namespaces
- [ ] NetworkPolicies
- [ ] Services
- [ ] Ingress policies
- [ ] Configmaps
- [ ] Secrets

**Comment by squaremo** [comment]
Bumping this out of the milestone, mainly to take it off the radar for now. It is still useful, though perhaps a bit less than we though, because re-applying the config in the sync loop tends to take care of many accidental divergences.

**Comment by sambooo** [comment]
Flux 1.* will apply whatever is in the git repo, overwriting any changes made with kubectl. This could be done more quickly with the implementation of #46, but otherwise this issue is resolved.
